swagger: '2.0'
info:
  version: "0.5.0"
  description: API to collect sensor and system information from facilities.
  title: Facility API
paths:
  /facilitydata:
    post:
      tags:
        - facilitydata
      summary: Add new facility data set
      description: Data from HVAC or BEMS systems
      operationId: addFacilityData
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: datavalue
          description: Facility data object
          required: true
          schema:
            items:
              $ref: "#/definitions/FacilityDataSet"
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "204":
          description: No content
        "400":
          description: Bad request
        "401":
          description: Unauthorized request
        "403":
          description: Forbidden
        "404":
          description: Resource not found
        "414":
          description: URI too long
        "429":
          description: Too many requests
  /sensordata:
    post:
      tags:
        - sensordata
      summary: Add new sensor data set
      description: Data from IoT sensors
      operationId: addSensorData
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: datavalue
          description: Sensor data object
          required: true
          schema: 
            $ref: "#/definitions/SensorDataSet"
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "204":
          description: No content
        "400":
          description: Bad request
        "401":
          description: Unauthorized request
        "403":
          description: Forbidden request
        "404":
          description: Resource not found
        "414":
          description: URI too long
        "429":
          description: Too many requests
  /sensorevent:
    post:
      tags:
        - sensorevent
      summary: Add new sensor event
      description: ""
      operationId: addSensorEvent
      parameters:
        - in: body
          name: datavalue
          description: Sensor event object
          required: true
          schema:
            $ref: "#/definitions/SensorEventData"
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "204":
          description: No content
        "400":
          description: Bad request
        "401":
          description: Unauthorized request
        "403":
          description: Forbidden
        "404":
          description: Resource not found
        "414":
          description: URI too long
        "429":
          description: Too many requests
definitions:
  FacilityDataSet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      property_id:
        type: string
      property_zip_code:
        type: integer
        format: int64
      measure_period_start:
        type: string
        format: date-time
        description: ISO8601
      measure_period_end:
        type: string
        format: date-time
        description: ISO8601
      valueSet:
        type: array
        items:
          $ref: "#/definitions/SensorDataValue"
  SensorDataSet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      DevEUI:
        type: string
      AppEUI:
        type: string
      valueSet:
        type: array
        items:
          $ref: "#/definitions/SensorDataValue"
  SensorEventData:
    type: object
    properties:
      DevEUI:
        type: string
      AppEUI:
        type: string
      Property_ID:
        type: string
      Property_Zip_Code:
        type: string
      Room_ID:
        type: string
      Floor_ID:
        type: string
      valueSet:
        $ref: "#/definitions/SensorDataValue"
  SensorDataValue:
    type: object
    properties:
      measure_time:
        type: string
        format: date-time
        description: ISO8601
      value:
        type: string
        description: Measurement value
      category:
        type: string
        enum:
        - SENSOR_CATEGORY_COMMON
        - SENSOR_CATEGORY_ELECTRICAL
        - SENSOR_CATEGORY_ENERGY
        - SENSOR_CATEGORY_ENVIRONMENTAL
        - SENSOR_CATEGORY_LIGHTING
        - SENSOR_CATEGORY_LOCATION
        - SENSOR_CATEGORY_MOTION
        - SENSOR_CATEGORY_MULTISENSOR
        - SENSOR_CATEGORY_PRESENCE
      valuetype:
        type: string
        description: Electrical sensor value types
        enum:
        - SENSOR_VALUETYPE_UNKNOWN
        - SENSOR_VALUETYPE_CAPACITANCE
        - SENSOR_VALUETYPE_RATED_CURRENT
        - SENSOR_VALUETYPE_PEAK_CURRENT
        - SENSOR_VALUETYPE_OPERATING_CURRENT
        - SENSOR_VALUETYPE_ACTIVE_POWER
        - SENSOR_VALUETYPE_REACTIVE_POWER
        - SENSOR_VALUETYPE_APPARENT_POWER
        - SENSOR_VALUETYPE_POWER_FACTOR
        - SENSOR_VALUETYPE_FREQUENCY
        - SENSOR_VALUETYPE_INDUCTANCE
        - SENSOR_VALUETYPE_IMPEDANCE
        - SENSOR_VALUETYPE_RESISTANCE
        - SENSOR_VALUETYPE_VOLTAGE
        - SENSOR_VALUETYPE_VOLTAGE_RMS
      dataunit:
        type: string
        description: Dataunits available for electrical values
        enum:
        - SENSOR_DATAUNIT_UNKNOWN
        - SENSOR_DATAUNIT_CAPACITANCE_FARAD
        - SENSOR_DATAUNIT_CURRENT_AMP
        - SENSOR_DATAUNIT_POWER_WATT
        - SENSOR_DATAUNIT_POWER_VAR
        - SENSOR_DATAUNIT_POWER_VOLTAMP
        - SENSOR_DATAUNIT_POWER_FACTOR_COSPHI
        - SENSOR_DATAUNIT_FREQUENCY_HERTZ
        - SENSOR_DATAUNIT_RESISTANCE_OHM
        - SENSOR_DATAUNIT_INDUCTANCE_HENRY
        - SENSOR_DATAUNIT_IMPEDANCE_OHM
        - SENSOR_DATAUNIT_VOLTAGE_VOLT
